name: First Workflow Practice
on:
  workflow_dispatch:
    branches:
      main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello from GitHub actions"
      - name: Print two variables
        run: |
          echo "Today is $(date)"
          echo "This message is sent from ${{ runner.os }}"
