name: CI for Python project
on: workflow_dispatch
jobs:
  Install-python-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Print cwd
        run: pwd
      - name: Print cwd2
        run: ls
      - name: print sad
        run: ls ..
