name: Check YAML syntax
on:
  push:
    paths:
      - "./config/**"
jobs:
  check-yaml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Check install lint
        run: |
          sudo apt-get install yamllint -y
          yamllint ./config